#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive

#installpkg(){
#    dpkg-query --status $1 >/dev/null || apt-get install -y $1
#}

updateAptGetPackages(){
	echo "Updating apt-get packages..."
	apt-get update
	echo -e "\tDONE::: Updating apt-get packages."
}

setupMySQL(){
	echo "Setting up MySQL..."
	debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
	debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
	apt-get install -y mysql-server
	service mysql restart
	mysql --user=root --password=root --host=127.0.0.1 --port=3306 --execute="CREATE DATABASE hello_django DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
	echo -e "\tDONE::: Setting up MySQL."
}

setupPythonVirtualEnv(){
	echo "Setting up VirtualEnv..."
	cd /home/vagrant
	mkdir environments
	chown -R vagrant environments/
	chgrp -R vagrant environments/
	cd ./environments
	wget https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.1.tar.gz
	tar zxvf ./virtualenv-15.0.1.tar.gz
	rm ./virtualenv-15.0.1.tar.gz
	python ./virtualenv-15.0.1/virtualenv.py ./hello-django-venv
	source ./hello-django-venv/bin/activate
	pip install --upgrade pip
	pip install ipython
	deactivate
	echo -e "\tDONE::: Setting up VirtualEnv."
}

installDjangoViaPip(){
	echo "Installing django via pip..."
	cd /home/vagrant
	source ./environments/hello-django-venv/bin/activate
	pip install Django==1.8.9
	deactivate
	echo -e "\tDONE::: Installing django via pip."
}

installMySQLdbDriversForDjango(){
	echo "Installing MySQL DB Drivers for Django..."
	apt-get install -y libmysqlclient-dev 
	apt-get install -y python-dev
	cd /home/vagrant
	source ./environments/hello-django-venv/bin/activate
	pip install mysqlclient
	deactivate
	echo -e "\tDONE::: Installing MySQL DB Drivers for Django."
}

DIYconfigureSettingsDotPy(){
	echo "DIY::: Configure mysite/mysite/settings.py to declare DB/timezone settings..."
	return
	# Use this JSON object as the value for DATABASES['default']:
	{
       'ENGINE':	'django.db.backends.mysql',
       'NAME':		'hello_django',
       'USER': 		'root',
       'PASSWORD':	'root',
       'HOST':		'127.0.0.1',
       'PORT':		'3306'
 	}
	# set TIME_ZONE = 
	"Asia/Dhaka"
}

updateAptGetPackages
setupMySQL
setupPythonVirtualEnv
installDjangoViaPip
installMySQLdbDriversForDjango
DIYconfigureSettingsDotPy

