#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive

#installpkg(){
#    dpkg-query --status $1 >/dev/null || apt-get install -y $1
#}

setupMySQL(){
	echo "Setting up MySQL..."
	apt-get update
	debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
	debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
	apt-get install -y mysql-server
	service mysql restart
	mysql --user=root --password=root --host=127.0.0.1 --port=3306 --execute="create database hello_django;"
	echo -e "\tDONE::: Setting up MySQL."
}

setupPythonVirtualEnv(){
	echo "Setting up VirtualEnv..."
	cd /home/vagrant
	wget https://pypi.python.org/packages/source/v/virtualenv/virtualenv-13.1.2.tar.gz
	tar zxvf ./virtualenv-13.1.2.tar.gz
	python ./virtualenv-13.1.2/virtualenv.py ./myDjangoVirtualEnv
	rm -r ./virtualenv-13.1.2/
	rm ./virtualenv-13.1.2.tar.gz
	source ./myDjangoVirtualEnv/bin/activate
	pip install ipython
	deactivate
	echo -e "\tDONE::: Setting up VirtualEnv."
}

installDjangoViaPip(){
	echo "Installing django via pip..."
	cd /home/vagrant
	source ./myDjangoVirtualEnv/bin/activate
	pip install django
	deactivate
	echo -e "\tDONE::: Installing django via pip."
}

startDjangoProject(){
	# This scope does not actually execute.
	# This scope only illustrates what shell commands you should run
	# to get a new django project started in this vagrant box. 
	return
	echo "DIY::: Start new django project 'mysite'..."
	cd /home/vagrant
	source ./myDjangoVirtualEnv/bin/activate
	cd ./sourcecodes
	django-admin startproject mysite # creates a bunch of files for the project
	mv mysite myproject
	deactivate
	cd ../
	echo -e "\tDIM::: Start new project 'mysite' - relocated to 'myproject'"
}

installMySQLdbDriversForDjango(){
	echo "Installing MySQL DB Drivers for Django..."
	apt-get install -y libmysqlclient-dev 
	apt-get install -y python-dev
	cd /home/vagrant
	source ./myDjangoVirtualEnv/bin/activate
	pip install mysqlclient
	deactivate
	echo -e "\tDONE::: Installing MySQL DB Drivers for Django."
}

setupMySQL
setupPythonVirtualEnv
installDjangoViaPip
startDjangoProject
installMySQLdbDriversForDjango